<div id="content_subpart_small">
	<div id="content_subpart_small_left">
		<h4>Par Chèque</h4>
		<p>Envoyer à</p>
		<p>
			Fondation du Patrimoine Délégation Régionale Midi-Pyrénées<br />
			11 Boulevard des Récollets<br />
			31078 TOULOUSE CEDEX 4
		<p>			
	</div>
	<div id="content_subpart_small_right">
		<h4>Par Carte Bancaire</h4>
		<p>Via notre <a class="normal" href="http://www.fondation-patrimoine.org/fr/midi-pyrenees-16/aides-au-patrimoine-1867/faites-un-don-a-un-projet-1894/soutenez-etape-2-3118/prjid-12971" target="blank">formulaire de don en ligne entièrement sécurisé</a></p>
		<p>
			N'oubliez pas de joindre le formulaire de don <a href='lib/script/download.php?type=pressreview&filename=souscription.pdf'><img src='img/icons/pdf.gif' alt='souscription.pdf' /></a> complété
			par vos soins pour que nous puissions vous envoyer votre reçu
			fiscal. 
		<p>			
	</div>
</div> 