<div id="content_subpart">
	<div class="separator">&nbsp;</div>
	<div id="content_info">
		<h3>Plus qu'un devoir de mémoire, un défi !</h3>
		<p>
			Réplic'Air construit le Morane-Saulnier type G <br>
			pour redonner la mémoire au pilote Roland Garros<br>
			et au constructeur Morane-Saulnier. Envolez-vous avec nous !<br>
			Rendez-vous le 23 Septembre 2013 pour célébrer le centenaire<br>
			de la traversée de la Méditerranée par les airs. 		
		<p>			
	</div>
	<div id="content_video">
		<div id="video">Loading the player ...</div>
	</div>
	<?php include($this->path . '/lib/includes/util/countdown.inc'); ?>
	<script type="text/javascript">
	    jwplayer("video").setup({
	        flashplayer: "player/player.swf",
	        file: "http://youtu.be/BaAUos7hcp0",
	        height: 170,
	        width: 170,
	        wmode:"transparent",
	        skin: "player/minima.zip"
	    });
	</script>
</div> 