<div id="general" class="compact" style="text-align:center;">
	<h3>Mentions</h3>
	
	<h4>Association</h4>
	<p  class="adresse" style="text-align: justify">Le site www.replicair.fr est la propriété de Replic’Air, Association loi 1901, reconnue d’utilité publique, dont le siège social est situé : </p>
	<p class="adresse">7 Chemin de Dardagna 31400 TOULOUSE</p>
	<p class="adresse">Tél. : 33 (0)6 58 16 23 55</p>
	<p class="adresse">Courriel : association.replicair@gmail.com</p>
</div>
<div id="equipe" class="compact" style="text-align: center;">
	<h4>Directeur de publication</h4>
	<p>Jérémy Caussade, Président de Réplic’Air</p>
	<h4>Communication</h4>
	<p>Arnaud Montoya</p>
</div>

<div id="equipe-left" class="compact" style="float: left;width: 380px">
	<h4>Conception du site</h4>
	<ul>
		<li>Conception et Rédaction : Arnaud Montroya</li>
		<li>WebDesigner : Arnaud Montoya , Sébastien Dominguez</li>
		<li>WebDevelopper : Ludovic Richert, Matthias Peuget</li>
		<li>Hébergement : matériels informatiques de la société OVH.net</li>
	</ul>
</div>
<div id="credits-right" class="compact" style="float: right; width:380px;">
	
	
	<h4>Crédits Photos</h4>
	<ul>
		<li>Musée Régional de l’air d’Angers ( Archives )</li>
		<li>Ludovic Lac ( Aéromodélisme )</li>
		<li>Anais Luneau ( Réplique )</li>
		<li>Arnaud Montoya ( Association )</li>
	</ul> 
</div>
<div style="clear: both"></div>
