<script>
        $(function(){
         	$("#partners-slideshow").slides({
              	effect: 'fade',
               	play: 5000,
               	pagination: true,
               	generatePagination: true,
               	generateNextPrev: true,
               	paginationClass: 'slidePagination_partner',
               	currentClass: 'slideCurrent_partner'
	        });
        });
</script>
<div id="content_top_big">
	<div id="partners-slideshow">
		<div class="slides_container">
			<div class="slides_content_partner">
				<div class="slide_center">
				<a href="http://www.lescasquesdecuir.com/index.php" target="blank"><img class="partners-logo" src="content/partners/partner-casquesdecuir.jpg" /></a>		
	   			<a href="http://www.fondation-patrimoine.org/" target="blank"><img class="partners-logo" src="content/partners/partner-fondationpatrimoine.jpg" /></a>
	    		<a href="http://www.pppdeluxe.com/" target="blank"><img class="partners-logo" src="content/partners/partner-pppdeluxe.jpg" /></a>
	    		</div>
	        </div>
	        <div class="slides_content_partner">
	        	<div class="slide_center">
				<a href="http://www.museeairespace.fr/" target="blank"><img class="partners-logo" src="content/partners/partner-museeairespace.jpg" /></a>
	    		<a href="http://www.musee-aviation-angers.fr/" target="blank"><img class="partners-logo" src="content/partners/partner-museeregionaldelair.jpg" /></a>
	    		<a href="http://www.hydravions-biscarrosse.com/002-musee/musee-accueil.php" target="blank"><img class="partners-logo" src="content/partners/partner-museehydraviationbiscarosse.jpg" /></a>
	    		</div>
	        </div>
	        <div class="slides_content_partner">
	        	<div class="slide_center">
				<a href="http://www.chalair.fr" target="blank"><img class="partners-logo" src="content/partners/partner-etoilechalair.jpg" /></a>
	    		<a href="http://www.derichebourg.com/pages_fr/multiservices/centre_formation_ms.php" target="blank"><img class="partners-logo" src="content/partners/partner-derichebourgevolutionformation.jpg" /></a>
	    		</div>
	        </div>
	    </div>
    </div>
    <div id="partners-content">
    	<h3>Devenez Pionnier</h3>
		<p>
			Ils sont nos partenaires depuis le début de cette aventure unique.
			Ce sont de réels Pionniers.
			Nous vous présentons ces pionniers.
		</p>	
		<p style="font-weight: bold; text-align: center">
			Vous possédez aussi cette âme de pionniers ?
		</p>
		<p>
			Nous vous invitons à la découvrir ou à la redécouvrir.
			Devenez partenaire de cette aventure unique.
			Vos dons pour la construction du Morane Saunlier type G et Réplic’Air seront déductible des impôts.
		</p> 
    </div>
</div>