<script>
        $(function(){
         	$("#partners-slideshow").slides({
              	effect: 'fade',
               	play: 5000,
               	pagination: true,
               	generatePagination: true,
               	generateNextPrev: true,
               	paginationClass: 'slidePagination_partner',
               	currentClass: 'slideCurrent_partner'
	        });
        });
</script>
<div id="content_top_big">
	<div id="partners-slideshow">
		<div class="slides_container">
			<div class="slides_content_partner">
				<div class="slide_center">
				<a><img class="partners-logo" src="content/partners/partner-chalair.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-AECF.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-DEF.png" /></a>
	    		</div>
	        </div>
	        <div class="slides_content_partner">
	        	<div class="slide_center">
	        	<a><img class="partners-logo" src="content/partners/partner-THALES.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-FDP.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-VECTO.png" /></a>
				
	    		</div>
	        </div>
	        <div class="slides_content_partner">
	        	<div class="slide_center">
	        	<a><img class="partners-logo" src="content/partners/partner-aerobuzz.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-AIRBUS.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-FUSIA.png" /></a>
				
	    		</div>
	        </div>
	        <div class="slides_content_partner">
	        	<div class="slide_center">
	        	<a><img class="partners-logo" src="content/partners/partner-CDC.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-MAE.png" /></a>
				<a><img class="partners-logo" src="content/partners/partner-MAA.png" /></a>
	    		</div>
	        </div>
	    </div>
    </div>
    <div id="partners-content">
    	<h3>Devenez Pionnier</h3>
		<p>
			Ils sont nos partenaires depuis le début de cette aventure unique.
			Ce sont de réels Pionniers.
			Nous vous présentons ces pionniers.
		</p>	
		<p style="font-weight: bold; text-align: center">
			Vous possédez aussi cette âme de pionniers ?
		</p>
		<p>
			Nous vous invitons à la découvrir ou à la redécouvrir.
			Devenez partenaire de cette aventure unique.
			Vos dons pour la construction du Morane Saunlier type G et Réplic’Air seront déductible des impôts.
		</p> 
    </div>
</div>