<div id="nav-top"><span style="margin-right: 55px;"><a href="contact.php">Contact</a></span> <span>fr</span> - <span style="color: black" title="A venir !">en</span></div>
<div id="nav">		
	<script type="text/javascript">
		$(document).ready(function(){
			$("#jMenu").jMenu({ ulWidth : 'auto', effects : { effectSpeedOpen : 300, effectTypeClose : 'slide' }, animatedText : false });
		});
	</script> 
	<ul id="jMenu">
		<li class="public"><a class="fNiv" href="index.php">Accueil</a></li>
		<li class="public"><a class="fNiv" href="article.php?category=replicair">Replic'Air</a></li>
		<li class="public"><a class="fNiv" href="article.php?category=project">Centen'Air</a></li>
		<li class="public"><a class="fNiv" href="article.php?category=legend">Legend'Air</a></li>
		<li class="public"><a class="fNiv" href="partenair.php">Partenaire</a></li>
		<li class="public"><a class="fNiv" href="pressreview-list.php">Revue de presse</a></li>
		<li class="public"><a class="fNiv" href="news-list.php">Actualités</a></li>
	</ul>
</div>