		<meta charset="utf-8"> 
		<title>Replic'Air</title>
		<meta name="description" content="LE MORANE-SAULNIER type G 1913" /> 
		<link rel="stylesheet" href="css/style-replicair.css" />
		<link rel="stylesheet" href="css/jmenu.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="css/jquery.mCustomScrollbar.css" />
		<!-- Hosting24 Analytics Code 
		<script type="text/javascript" src="http://stats.hosting24.com/count.php"></script>
		--><!-- End Of Analytics Code 
		<script type="text/javascript">

			  var _gaq = _gaq || [];
			  _gaq.push(['_setAccount', 'UA-32198137-1']);
			  _gaq.push(['_trackPageview']);
			
			  (function() {
			    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			  })();

		</script>-->
		<script type="text/javascript" src="js/swfobject-2.2.js"></script>
		<script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.8.23.custom.min.js"></script>
		<script type="text/javascript" src="js/jmenu.min.jquery.js"></script>
		<script type="text/javascript" src="js/slides.jquery.js"></script>
		<script type="text/javascript" src="js/jquery.mousewheel.min.js"></script>
		<script type="text/javascript" src="js/jquery.mCustomScrollbar.min.js"></script>
		<script type="text/javascript" src="player/jwplayer.js"></script>
		<script type="text/javascript"  src="galleria/galleria-1.2.8.min.js"></script>
		<script type="text/javascript"  src="galleria/plugins/picasa/galleria.picasa.js"></script>