	<meta charset="utf-8"> 
	<title>Replic'Air Administration</title>
	<link rel="stylesheet" href="../css/style-replicair.css" />
	<link rel="stylesheet" href="../css/admin.css" />
	<link rel="stylesheet" href="../css/jmenu.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="../css/ui-lightness/jquery-ui-1.8.23.custom.css" />
	<link rel="stylesheet" href="../css/jquery.mCustomScrollbar.css" />
	<script type="text/javascript" src="../js/jquery-1.8.0.min.js"></script>
	<script type="text/javascript" src="../js/slides.jquery.js"></script>
	<script type="text/javascript" src="../js/filestyle.min.jquery.js"></script>
	<script type="text/javascript" src="ckeditor/ckeditor.js"></script>
	<!-- <script type="text/javascript" src="/js/jquery-ui.js"></script>-->
	<script type="text/javascript" src="../js/jquery-ui-1.8.23.custom.min.js"></script>
	<script type="text/javascript" src="../js/jmenu.min.jquery.js"></script>
	<script type="text/javascript" src="../js/jquery.mousewheel.min.js"></script>
	<script type="text/javascript" src="../js/jquery.mCustomScrollbar.min.js"></script>
	<script type="text/javascript" charset="utf-8">
	$(function() {
	      $("input[type=file]").filestyle({ 
	     image: "../img/style/button-choosefile.gif",
	     imageheight : 22,
	     imagewidth : 82,
	     width : 445
	 		});
	});
	</script>
