		<meta charset="utf-8"> 
		<title>Replic'Air</title>
		<meta name="description" content="LE MORANE-SAULNIER type G 1913" /> 
		<link rel="stylesheet" href="css/style-replicair.css" />
		<link rel="stylesheet" href="css/jmenu.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="css/jquery.mCustomScrollbar.css" />
		<?php include_once($this->path . "/lib/includes/header/google-analytics.inc") ?>
		<script type="text/javascript" src="js/swfobject-2.2.js"></script>
		<script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.8.23.custom.min.js"></script>
		<script type="text/javascript" src="js/jmenu.min.jquery.js"></script>
		<script type="text/javascript" src="js/slides.jquery.js"></script>
		<script type="text/javascript" src="js/jquery.mousewheel.min.js"></script>
		<script type="text/javascript" src="js/jquery.mCustomScrollbar.min.js"></script>
		<script type="text/javascript" src="player/jwplayer.js"></script>
		<script type="text/javascript"  src="galleria/galleria-1.2.8.min.js"></script>
		<script type="text/javascript"  src="galleria/plugins/picasa/galleria.picasa.js"></script>