<div id="middle-mid">
				<?php include('../lib/includes/nav/nav-admin.inc'); ?>
				<div id="content" class="content-normal">
				    <div id="content_top">
            			<div class="slides_container">
                			<div class="slides_content">
                				<div class="slide_desc" style="text-align: justify">
                					<h3>Gestion du contenu</h3>
                					<p>Cette partie vous permet de gérer le contenu du site : articles, news, revue de presse...</p>
                					<p>Vous pourrez créer, modifier, activer (ou désactiver) le contenu.</p>
                				</div>
                    			<img src="<?php echo $this->root ?>content/admin/admin-content.jpg" alt="gestion-contenu" />
                			</div>
                			<div class="slides_content">
                				<div class="slide_desc" style="text-align: justify">
                					<h3>Aide à la saisie</h3>
                					<p>Des tooltips sont présent sur les champs pour vous orienter sur la manière de les renseigner.</p>
                					<p>Laisser votre souris sur le nom du champs pour obtenir ces informations !</p>
                				</div>
                    			<img src="<?php echo $this->root ?>content/admin/admin-typing.jpg" alt="aide-saisie"/>
                			</div>
                			<div class="slides_content">
                			    <div class="slide_desc" style="text-align: justify">
                					<h3>Vérification</h3>
                					<p>Pour tous les contenus, vous pouvez les visualiser tels qu'ils apparaitront.</p>
                					<p>A vous de choisir de les activer si vous voulez les rendre disponible sur le site public.</p>
                				</div>
                    			<img src="<?php echo $this->root ?>content/admin/admin-check.jpg" alt="verification"/>
                			</div>
            			</div>
        			</div>
					<div id="content_subpart" style="text-align:center;">						
							<h3 style="margin-top: 10px;">Bienvenue !</h3>
							<p>Bienvenue dans la partie Administration du site<p>
							<p>Dans cette partie vous pourrez intéragir avec le contenu du site de manière immédiate :<p>
							<ul style="text-align: left; margin-left: 280px;">
								<li>Gérer les news</li>
								<li>Gérer la revue de presse</li>
								<li>Gérer le slideshow d'accueil</li>
								<li>Gérer la timeline</li>
								<li>...</li>
							</ul>			
					</div> 
				</div>
</div>