<div id="middle-mid">
	<?php include('../lib/includes/nav/nav-admin.inc'); ?>
	<div id="content" class="content-normal">
		<div style="padding-top: 50px; padding-bottom: 20px;">
		<img alt="crash ?" src="../img/various/error.jpg" style="display:block; margin: auto; border: 1px solid black; " />
		</div>
		<p class="simple" style="text-align:center; font-weight: bold;"><?php echo $this->message ?></p>
	</div>
</div>