<!-- facebook -->
<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode("http://www.replicair.fr"); ?>&amp;send=false&amp;layout=button_count&amp;width=200&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0"  class="facebook-like" allowTransparency="true"></iframe>

<!-- tweeter -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.replicair.fr" data-text="texte a partager" data-lang="fr" class="tweeter-like">Tweeter</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<!-- google+ -->
<div class="g-plusone" data-size="medium" data-href="http://www.replicair.fr"></div>
<script type="text/javascript">
  window.___gcfg = {lang: 'fr'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>